name: Build & Deploy 🚀
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'
      - 'img/**'

jobs:
  converttopdf:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: src
          output_dir: build
          images_dir: img
          image_import: ./img
          build_html: true
          build_pdf: true
          table_of_contents: true
      - name: Deploy Github pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "PDF Build"
          files: |
            build/index.pdf
